// Fundraising Command Centre (FCC) MVP core measures
// Assumptions:
// - These measures use the Sprint 2 base table names from powerbi/m/*.pq.
// - Natural ID relationships are assumed for the MVP model.
// - Activities are intentionally excluded from the core semantic model.
// - readiness_score and risk_score are imported Initiative inputs only.
// - Metric snapshot measures read imported snapshot rows; they do not calculate readiness or compliance.
// - Count snapshot metrics sum across visible Initiatives at the latest snapshot date.
// - Placeholder compliance metrics use simple averages until numerator/denominator fields exist.
// - Knowledge status is not mixed into operational status measures.

// -----------------------------------------------------------------------------
// Commitments
// -----------------------------------------------------------------------------

Open Commitments =
CALCULATE (
    COUNTROWS ( Commitments ),
    FILTER (
        Commitments,
        NOT ( Commitments[status] IN { "Completed", "Complete" } )
    )
)

Completed Commitments =
CALCULATE (
    COUNTROWS ( Commitments ),
    Commitments[status] IN { "Completed", "Complete" }
)

Overdue Commitments =
CALCULATE (
    COUNTROWS ( Commitments ),
    FILTER (
        Commitments,
        Commitments[due_date] < TODAY ()
            && NOT ( Commitments[status] IN { "Completed", "Complete" } )
    )
)

Commitments Due Next 7 Days =
CALCULATE (
    COUNTROWS ( Commitments ),
    FILTER (
        Commitments,
        Commitments[due_date] >= TODAY ()
            && Commitments[due_date] <= TODAY () + 7
            && NOT ( Commitments[status] IN { "Completed", "Complete" } )
    )
)

Commitment Completion Rate =
DIVIDE (
    [Completed Commitments],
    COUNTROWS ( Commitments )
)

// -----------------------------------------------------------------------------
// Dependencies
// -----------------------------------------------------------------------------

Open Dependencies =
CALCULATE (
    COUNTROWS ( Dependencies ),
    FILTER (
        Dependencies,
        NOT ( Dependencies[status] IN { "Resolved" } )
    )
)

Resolved Dependencies =
CALCULATE (
    COUNTROWS ( Dependencies ),
    Dependencies[status] = "Resolved"
)

Overdue Dependencies =
CALCULATE (
    COUNTROWS ( Dependencies ),
    FILTER (
        Dependencies,
        Dependencies[due_date] < TODAY ()
            && NOT ( Dependencies[status] IN { "Resolved" } )
    )
)

High Severity Dependencies =
CALCULATE (
    COUNTROWS ( Dependencies ),
    FILTER (
        Dependencies,
        Dependencies[severity] = "High"
            && NOT ( Dependencies[status] IN { "Resolved" } )
    )
)

// -----------------------------------------------------------------------------
// Risks
// -----------------------------------------------------------------------------

Open Risks =
CALCULATE (
    COUNTROWS ( Risks ),
    FILTER (
        Risks,
        NOT ( Risks[status] IN { "Resolved" } )
    )
)

High Risks =
CALCULATE (
    COUNTROWS ( Risks ),
    FILTER (
        Risks,
        Risks[severity] = "High"
            && NOT ( Risks[status] IN { "Resolved" } )
    )
)

Critical Risks =
CALCULATE (
    COUNTROWS ( Risks ),
    FILTER (
        Risks,
        Risks[severity] = "Critical"
            && NOT ( Risks[status] IN { "Resolved" } )
    )
)

Resolved Risks =
CALCULATE (
    COUNTROWS ( Risks ),
    Risks[status] = "Resolved"
)

Initiatives At Risk =
CALCULATE (
    DISTINCTCOUNT ( Risks[initiative] ),
    FILTER (
        Risks,
        Risks[severity] IN { "High", "Critical" }
            && NOT ( Risks[status] IN { "Resolved" } )
    )
)

// -----------------------------------------------------------------------------
// Metric Snapshots
// -----------------------------------------------------------------------------

Latest Snapshot Date =
MAX ( MetricSnapshots[snapshot_date] )

Open Commitments Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "open_commitments_count"
    )
RETURN
    CALCULATE (
        SUM ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "open_commitments_count",
        MetricSnapshots[snapshot_date] = LatestDate
    )

Overdue Commitments Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "overdue_commitments_count"
    )
RETURN
    CALCULATE (
        SUM ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "overdue_commitments_count",
        MetricSnapshots[snapshot_date] = LatestDate
    )

Open Dependencies Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "open_dependencies_count"
    )
RETURN
    CALCULATE (
        SUM ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "open_dependencies_count",
        MetricSnapshots[snapshot_date] = LatestDate
    )

High Risks Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "high_risks_count"
    )
RETURN
    CALCULATE (
        SUM ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "high_risks_count",
        MetricSnapshots[snapshot_date] = LatestDate
    )

Follow-Up Compliance Placeholder Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "follow_up_compliance"
    )
RETURN
    CALCULATE (
        AVERAGE ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "follow_up_compliance",
        MetricSnapshots[snapshot_date] = LatestDate
    )

Commitment Compliance Placeholder Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "commitment_compliance"
    )
RETURN
    CALCULATE (
        AVERAGE ( MetricSnapshots[metric_value] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "commitment_compliance",
        MetricSnapshots[snapshot_date] = LatestDate
    )

Readiness Score Placeholder Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "readiness_score_placeholder"
    )
RETURN
    IF (
        HASONEVALUE ( Initiatives[initiative_id] ),
        CALCULATE (
            MAX ( MetricSnapshots[metric_value] ),
            ALL ( MetricSnapshots[metric_name] ),
            MetricSnapshots[metric_name] = "readiness_score_placeholder",
            MetricSnapshots[snapshot_date] = LatestDate
        ),
        BLANK ()
    )

Risk Score Placeholder Latest =
VAR LatestDate =
    CALCULATE (
        MAX ( MetricSnapshots[snapshot_date] ),
        ALL ( MetricSnapshots[metric_name] ),
        MetricSnapshots[metric_name] = "risk_score_placeholder"
    )
RETURN
    IF (
        HASONEVALUE ( Initiatives[initiative_id] ),
        CALCULATE (
            MAX ( MetricSnapshots[metric_value] ),
            ALL ( MetricSnapshots[metric_name] ),
            MetricSnapshots[metric_name] = "risk_score_placeholder",
            MetricSnapshots[snapshot_date] = LatestDate
        ),
        BLANK ()
    )

// -----------------------------------------------------------------------------
// Initiatives
// -----------------------------------------------------------------------------

Active Initiatives =
CALCULATE (
    COUNTROWS ( Initiatives ),
    FILTER (
        Initiatives,
        NOT ( Initiatives[status] IN { "Completed", "Complete", "Closed" } )
    )
)

Completed Initiatives =
CALCULATE (
    COUNTROWS ( Initiatives ),
    Initiatives[status] IN { "Completed", "Complete" }
)

Average Readiness Score =
AVERAGE ( Initiatives[readiness_score] )

Average Risk Score =
AVERAGE ( Initiatives[risk_score] )
